name: "Exercicio 2"

on:
  push:

jobs:
  cria_upload_artefato:
    name: "Cria Upload e faz Artefato"
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout_Repositorio
        uses: actions/checkout@v3.3.0
