name: "Exercicio 2"

on:
  push:

jobs:
  cria_upload_artefato:
    name: "Cria Upload e faz Artefato"
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout_Repositorio
        uses: actions/checkout@v3.3.0

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{vars.NOME_ARQUIVO_UPLOAD }}
          path: .
          retention_days: 15
